#!/bin/sh
# USB modem hotplug handler
# Automatically configures USB modems as additional WANs when plugged in

[ "$ACTION" = "add" ] || exit 0

# Only handle USB network devices and modems
case "$DEVTYPE" in
    usb_interface|usb_device)
        # Check if this is a modem-related device
        case "$PRODUCT" in
            # Quectel modems
            2c7c/*)
                logger -t usb-modem-hotplug "Quectel modem detected: $PRODUCT"
                ;;
            # Huawei modems
            12d1/*)
                logger -t usb-modem-hotplug "Huawei modem detected: $PRODUCT"
                ;;
            # Sierra Wireless
            1199/*)
                logger -t usb-modem-hotplug "Sierra Wireless modem detected: $PRODUCT"
                ;;
            # ZTE modems
            19d2/*)
                logger -t usb-modem-hotplug "ZTE modem detected: $PRODUCT"
                ;;
            # SIMCom modems
            1e0e/*)
                logger -t usb-modem-hotplug "SIMCom modem detected: $PRODUCT"
                ;;
            # Fibocom modems
            2cb7/*)
                logger -t usb-modem-hotplug "Fibocom modem detected: $PRODUCT"
                ;;
            # Telit modems
            1bc7/*)
                logger -t usb-modem-hotplug "Telit modem detected: $PRODUCT"
                ;;
            # MediaTek modems (Fibocom FM350-GL)
            0e8d/*)
                logger -t usb-modem-hotplug "MediaTek/Fibocom modem detected: $PRODUCT"
                ;;
            *)
                # Not a known modem, skip
                exit 0
                ;;
        esac
        
        # Wait a bit for device to fully enumerate
        sleep 5

        # Run USB modem auto-config with lock to prevent race conditions
        # Multiple rapid plug/unplug events could spawn duplicate configs
        if [ -x /usr/bin/usb-modem-autoconfig.sh ]; then
            LOCK_FILE="/var/lock/usb-modem-autoconfig.lock"
            (
                # Non-blocking lock - exit if another instance is running
                flock -n 200 || exit 0
                /usr/bin/usb-modem-autoconfig.sh
            ) 200>"$LOCK_FILE" &
        fi
        ;;
esac

exit 0
