#!/bin/sh /etc/rc.common
# MPTCP Manager Service - Intelligent path management for OpenMPTCProuter
# Starts both metrics exporter and path manager daemons

START=99
STOP=10

USE_PROCD=1

start_service() {
    # Start metrics exporter
    procd_open_instance metrics-exporter
    procd_set_param command /usr/bin/mptcp-metrics-exporter
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance

    # Start path manager (depends on metrics)
    procd_open_instance path-manager
    procd_set_param command /usr/bin/mptcp-path-manager
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance

    logger -t mptcp-manager "MPTCP intelligent path management started"
}

stop_service() {
    logger -t mptcp-manager "MPTCP intelligent path management stopped"
}

service_triggers() {
    procd_add_reload_trigger "network"
}
